pipeline {
    agent any

    tools {
        maven 'M3' // Make sure 'M3' matches the name you configured in Jenkins tools
    }

    stages {
        stage('Build with Maven') {
            steps {
                dir('MyMavenapp') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
